
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GroupSports.DL.DM
{

using System;
    using System.Collections.Generic;
    
public partial class athleteAchievement
{

    public int id { get; set; }

    public int athleteAchievementTypeId { get; set; }

    public int place { get; set; }

    public string description { get; set; }

    public int athleteId { get; set; }

    public bool available { get; set; }

    public Nullable<System.TimeSpan> resultTime { get; set; }

    public Nullable<double> resultDistance { get; set; }



    [Newtonsoft.Json.JsonIgnore] public virtual athelete athelete { get; set; }

    public virtual athleteAchievementType athleteAchievementType { get; set; }

}

}
