
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GroupSports.DL.DM
{

using System;
    using System.Collections.Generic;
    
public partial class athleteDetails
{

    public int id { get; set; }

    public Nullable<double> weight { get; set; }

    public Nullable<double> height { get; set; }

    public Nullable<double> bodySpan { get; set; }

    public Nullable<double> legLength { get; set; }

    public Nullable<double> halfSquatToFloor { get; set; }

    public string shirtSize { get; set; }

    public string pantsSize { get; set; }

    public string footwearSize { get; set; }

    public int athleteId { get; set; }

    public bool available { get; set; }



    [Newtonsoft.Json.JsonIgnore] public virtual athelete athelete { get; set; }

}

}
