
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GroupSports.DL.DM
{

using System;
    using System.Collections.Generic;
    
public partial class competitionByCoach
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public competitionByCoach()
    {

        this.competitionHurdlesTest = new HashSet<competitionHurdlesTest>();

        this.competitionJumpTest = new HashSet<competitionJumpTest>();

        this.competitionLongDistanceTest = new HashSet<competitionLongDistanceTest>();

        this.competitionMiddleDistanceTest = new HashSet<competitionMiddleDistanceTest>();

        this.competitionRaceWalkingTest = new HashSet<competitionRaceWalkingTest>();

        this.competitionRelaysTest = new HashSet<competitionRelaysTest>();

        this.competitionSprintsTest = new HashSet<competitionSprintsTest>();

        this.competitionThrowsTest = new HashSet<competitionThrowsTest>();

    }


    public int id { get; set; }

    public Nullable<int> competitionId { get; set; }

    public string competitionName { get; set; }

    public int year { get; set; }

    public int coachId { get; set; }

    public bool available { get; set; }



    [Newtonsoft.Json.JsonIgnore] public virtual coach coach { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual competition competition { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    [Newtonsoft.Json.JsonIgnore] public virtual ICollection<competitionHurdlesTest> competitionHurdlesTest { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    [Newtonsoft.Json.JsonIgnore] public virtual ICollection<competitionJumpTest> competitionJumpTest { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    [Newtonsoft.Json.JsonIgnore] public virtual ICollection<competitionLongDistanceTest> competitionLongDistanceTest { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    [Newtonsoft.Json.JsonIgnore] public virtual ICollection<competitionMiddleDistanceTest> competitionMiddleDistanceTest { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    [Newtonsoft.Json.JsonIgnore] public virtual ICollection<competitionRaceWalkingTest> competitionRaceWalkingTest { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    [Newtonsoft.Json.JsonIgnore] public virtual ICollection<competitionRelaysTest> competitionRelaysTest { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    [Newtonsoft.Json.JsonIgnore] public virtual ICollection<competitionSprintsTest> competitionSprintsTest { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    [Newtonsoft.Json.JsonIgnore] public virtual ICollection<competitionThrowsTest> competitionThrowsTest { get; set; }

}

}
