

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GroupSports.DL.DM
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class group_sportsEntities : DbContext
{
    public group_sportsEntities()
        : base("name=group_sportsEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<announcement> announcement { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<announcementByAthlete> announcementByAthlete { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<anthropometricTest> anthropometricTest { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<athelete> athelete { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<atheleteByParameter> atheleteByParameter { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<atheleteByTeam> atheleteByTeam { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<athleteAchievement> athleteAchievement { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<athleteAchievementType> athleteAchievementType { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<athleteDetails> athleteDetails { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<athleteFoda> athleteFoda { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<athleteQuiz> athleteQuiz { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<binnacleDetail> binnacleDetail { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<coach> coach { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<coachByAthelete> coachByAthelete { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<coachByTeam> coachByTeam { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<coachCurriculumDetail> coachCurriculumDetail { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<colorOfMood> colorOfMood { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<competition> competition { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<competitionByCoach> competitionByCoach { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<competitionHurdlesTest> competitionHurdlesTest { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<competitionJumpTest> competitionJumpTest { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<competitionJumpTestType> competitionJumpTestType { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<competitionLongDistanceTest> competitionLongDistanceTest { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<competitionMiddleDistanceTest> competitionMiddleDistanceTest { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<competitionRaceWalkingTest> competitionRaceWalkingTest { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<competitionRelaysTest> competitionRelaysTest { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<competitionRelayType> competitionRelayType { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<competitionSprintsTest> competitionSprintsTest { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<competitionThrowsTest> competitionThrowsTest { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<competitionThrowsTestType> competitionThrowsTestType { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<discipline> discipline { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<fodaItemType> fodaItemType { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<jumpTest> jumpTest { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<jumpTestType> jumpTestType { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<mesocycle> mesocycle { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<mesocycleType> mesocycleType { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<mood> mood { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<parameter> parameter { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<question> question { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<questionBySession> questionBySession { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<quiz> quiz { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<quizQuestion> quizQuestion { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<quizQuestionByAthlete> quizQuestionByAthlete { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<resistanceTest> resistanceTest { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<session> session { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<shift> shift { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<shotPutTest> shotPutTest { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<shotPutType> shotPutType { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<speedTest> speedTest { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<strengthTest> strengthTest { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<strengthTestType> strengthTestType { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<team> team { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<trainingPlan> trainingPlan { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<user> user { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<week> week { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<weekType> weekType { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<weightTestBySession> weightTestBySession { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<activeCaloriesWearable> activeCaloriesWearable { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<heartRateWearable> heartRateWearable { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual DbSet<stepsCountWearable> stepsCountWearable { get; set; }

}

}

