
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GroupSports.DL.DM
{

using System;
    using System.Collections.Generic;
    
public partial class mesocycle
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public mesocycle()
    {

        this.week = new HashSet<week>();

    }


    public int id { get; set; }

    public int trainingPlanId { get; set; }

    public int numberOfIntenseWeeks { get; set; }

    public int numberOfRestWeeks { get; set; }

    public Nullable<System.DateTime> startDate { get; set; }

    public Nullable<System.DateTime> endDate { get; set; }

    public int mesocycleTypeId { get; set; }

    public bool available { get; set; }



    public virtual mesocycleType mesocycleType { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual trainingPlan trainingPlan { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    [Newtonsoft.Json.JsonIgnore] public virtual ICollection<week> week { get; set; }

}

}
