
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GroupSports.DL.DM
{

using System;
    using System.Collections.Generic;
    
public partial class quizQuestion
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public quizQuestion()
    {

        this.quizQuestionByAthlete = new HashSet<quizQuestionByAthlete>();

    }


    public int id { get; set; }

    public int quizId { get; set; }

    public string questionTitle { get; set; }

    public bool available { get; set; }



    [Newtonsoft.Json.JsonIgnore] public virtual quiz quiz { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    [Newtonsoft.Json.JsonIgnore] public virtual ICollection<quizQuestionByAthlete> quizQuestionByAthlete { get; set; }

}

}
