
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GroupSports.DL.DM
{

using System;
    using System.Collections.Generic;
    
public partial class quizQuestionByAthlete
{

    public int id { get; set; }

    public int quizQuestionId { get; set; }

    public string answer { get; set; }

    public int athleteQuizId { get; set; }

    public bool available { get; set; }



    [Newtonsoft.Json.JsonIgnore] public virtual athleteQuiz athleteQuiz { get; set; }

    public virtual quizQuestion quizQuestion { get; set; }

}

}
