
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GroupSports.DL.DM
{

using System;
    using System.Collections.Generic;
    
public partial class session
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public session()
    {

        this.binnacleDetail = new HashSet<binnacleDetail>();

        this.jumpTest = new HashSet<jumpTest>();

        this.questionBySession = new HashSet<questionBySession>();

        this.resistanceTest = new HashSet<resistanceTest>();

        this.shotPutTest = new HashSet<shotPutTest>();

        this.speedTest = new HashSet<speedTest>();

        this.strengthTest = new HashSet<strengthTest>();

        this.weightTestBySession = new HashSet<weightTestBySession>();

    }


    public int id { get; set; }

    public System.DateTime sessionDay { get; set; }

    public Nullable<double> intensityPercentage { get; set; }

    public int shiftId { get; set; }

    public int weekId { get; set; }

    public int coachId { get; set; }

    public int athleteId { get; set; }

    public bool attendance { get; set; }

    public bool available { get; set; }



    [Newtonsoft.Json.JsonIgnore] public virtual athelete athelete { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    [Newtonsoft.Json.JsonIgnore] public virtual ICollection<binnacleDetail> binnacleDetail { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual coach coach { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    [Newtonsoft.Json.JsonIgnore] public virtual ICollection<jumpTest> jumpTest { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    [Newtonsoft.Json.JsonIgnore] public virtual ICollection<questionBySession> questionBySession { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    [Newtonsoft.Json.JsonIgnore] public virtual ICollection<resistanceTest> resistanceTest { get; set; }

    public virtual shift shift { get; set; }

    [Newtonsoft.Json.JsonIgnore] public virtual week week { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    [Newtonsoft.Json.JsonIgnore] public virtual ICollection<shotPutTest> shotPutTest { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    [Newtonsoft.Json.JsonIgnore] public virtual ICollection<speedTest> speedTest { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    [Newtonsoft.Json.JsonIgnore] public virtual ICollection<strengthTest> strengthTest { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    [Newtonsoft.Json.JsonIgnore] public virtual ICollection<weightTestBySession> weightTestBySession { get; set; }

}

}
