
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GroupSports.DL.DM
{

using System;
    using System.Collections.Generic;
    
public partial class user
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public user()
    {

        this.athelete = new HashSet<athelete>();

        this.coach = new HashSet<coach>();

    }


    public int id { get; set; }

    public string username { get; set; }

    public string password { get; set; }

    public int userType { get; set; }

    public string firstName { get; set; }

    public string lastName { get; set; }

    public string cellPhone { get; set; }

    public string address { get; set; }

    public string emailAddress { get; set; }

    public string pictureUrl { get; set; }

    public System.DateTime birthDate { get; set; }

    public bool available { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    [Newtonsoft.Json.JsonIgnore] public virtual ICollection<athelete> athelete { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    [Newtonsoft.Json.JsonIgnore] public virtual ICollection<coach> coach { get; set; }

}

}
