
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GroupSports.DL.DM
{

using System;
    using System.Collections.Generic;
    
public partial class week
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public week()
    {

        this.session = new HashSet<session>();

    }


    public int id { get; set; }

    public int weekTypeId { get; set; }

    public System.DateTime startDate { get; set; }

    public System.DateTime endDate { get; set; }

    public int mesocycleId { get; set; }

    public string activity { get; set; }

    public bool available { get; set; }



    [Newtonsoft.Json.JsonIgnore] public virtual mesocycle mesocycle { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    [Newtonsoft.Json.JsonIgnore] public virtual ICollection<session> session { get; set; }

    public virtual weekType weekType { get; set; }

}

}
